# Generated by Django 4.2.8 on 2026-06-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('device_type', models.CharField(max_length=50, verbose_name='Тип устройства')),
                ('status', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], max_length=20, verbose_name='Статус')),
                ('power_state', models.CharField(choices=[('on', 'Включено'), ('off', 'Выключено')], max_length=20, verbose_name='Состояние')),
                ('current_power', models.FloatField(default=0, verbose_name='Текущая мощность (кВт)')),
                ('rated_power', models.FloatField(verbose_name='Номинальная мощность (кВт)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('action', models.CharField(choices=[('on', 'Включить'), ('off', 'Отключить')], max_length=10, verbose_name='Действие')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100, verbose_name='Тип ошибки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Серьезность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Ошибка устройства',
                'verbose_name_plural': 'Ошибки устройств',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип действия')),
                ('details', models.JSONField(verbose_name='Детали')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Действие устройства',
                'verbose_name_plural': 'Действия устройств',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_update'], name='devices_dev_last_up_c4d978_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['created_at'], name='devices_dev_created_f36e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['device', 'enabled'], name='devices_sch_device__4f681b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['time'], name='devices_sch_time_5ff3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaction',
            index=models.Index(fields=['device', 'timestamp'], name='devices_dev_device__63ef8e_idx'),
        ),
    ]
