# Generated by Django 4.2.8 on 2026-06-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['created_at'], 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
    ]
