# Generated by Django 4.2.8 on 2026-06-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(verbose_name='Мощность (кВт)')),
                ('energy', models.FloatField(verbose_name='Энергия (кВт·ч)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Потребление энергии',
                'verbose_name_plural': 'Потребления энергии',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='energy_ener_device__38e535_idx'), models.Index(fields=['timestamp'], name='energy_ener_timesta_e570b6_idx'), models.Index(fields=['device'], name='energy_ener_device__8efb75_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_energy', models.FloatField(verbose_name='Общая энергия (кВт·ч)')),
                ('avg_power', models.FloatField(verbose_name='Средняя мощность (кВт)')),
                ('peak_power', models.FloatField(verbose_name='Пиковая мощность (кВт)')),
                ('cost', models.FloatField(verbose_name='Стоимость (₽)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Суточная статистика',
                'verbose_name_plural': 'Суточные статистики',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='energy_dail_date_89a1dc_idx'), models.Index(fields=['device', 'date'], name='energy_dail_device__38b08f_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
