# Generated by Django 4.2.8 on 2026-06-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('schedule', 'Настройка расписания'), ('night_shift', 'Перенос на ночь'), ('replacement', 'Замена устройства'), ('preset', 'Готовый сценарий')], max_length=50, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('current_cost', models.FloatField(default=0, verbose_name='Текущая стоимость (₽/мес)')),
                ('estimated_savings', models.FloatField(default=0, verbose_name='Экономия (₽/мес)')),
                ('savings_percent', models.FloatField(default=0, verbose_name='Экономия (%)')),
                ('implemented', models.BooleanField(default=False, verbose_name='Применено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-estimated_savings'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('ml_anomaly', 'Аномалия ML'), ('overload', 'Перегрузка'), ('forgotten', 'Забытое устройство'), ('night_work', 'Ночная работа'), ('high_baseline', 'Высокий фон'), ('spike', 'Резкий скачок')], max_length=50, verbose_name='Тип')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Серьёзность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ml_score', models.FloatField(blank=True, null=True, verbose_name='Оценка ML')),
                ('current_value', models.FloatField(default=0, verbose_name='Текущее значение')),
                ('expected_value', models.FloatField(default=0, verbose_name='Ожидаемое значение')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Обнаружено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Аномалия',
                'verbose_name_plural': 'Аномалии',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['device', 'resolved_at'], name='energy_anom_device__2137a5_idx'), models.Index(fields=['severity'], name='energy_anom_severit_c27a81_idx')],
            },
        ),
    ]
