# Generated by Django 4.2.8 on 2026-06-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options'),
        ('energy', '0002_savingrecommendation_anomalyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('overload', 'Перегрузка'), ('night_work', 'Ночная работа'), ('forgotten', 'Забытое устройство'), ('ml_anomaly', 'Аномалия ML')], max_length=50, verbose_name='Тип')),
                ('load_ratio', models.FloatField(default=0, verbose_name='Загрузка (%)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_logs', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Лог аномалии',
                'verbose_name_plural': 'Логи аномалий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='energy_anom_device__6afbe9_idx'), models.Index(fields=['anomaly_type'], name='energy_anom_anomaly_89e3bf_idx')],
            },
        ),
    ]
